// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiHYoyd3AypCiNjVOrS9W9wScI-b5PJhU',
    appId: '1:221902786162:web:14751d7a869f5043127ceb',
    messagingSenderId: '221902786162',
    projectId: 'coin-2ff5f',
    authDomain: 'coin-2ff5f.firebaseapp.com',
    storageBucket: 'coin-2ff5f.firebasestorage.app',
    measurementId: 'G-ND2HY41LG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbN03W-6hE7DyeyXEfGsq4rMVlq-DI1ds',
    appId: '1:221902786162:android:d44ab74c03722e1a127ceb',
    messagingSenderId: '221902786162',
    projectId: 'coin-2ff5f',
    storageBucket: 'coin-2ff5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY78RKRlDp5fwr5BwNonwrvwTArPQ0hDA',
    appId: '1:221902786162:ios:478800cf7324de06127ceb',
    messagingSenderId: '221902786162',
    projectId: 'coin-2ff5f',
    storageBucket: 'coin-2ff5f.firebasestorage.app',
    iosBundleId: 'com.example.attendancePanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY78RKRlDp5fwr5BwNonwrvwTArPQ0hDA',
    appId: '1:221902786162:ios:478800cf7324de06127ceb',
    messagingSenderId: '221902786162',
    projectId: 'coin-2ff5f',
    storageBucket: 'coin-2ff5f.firebasestorage.app',
    iosBundleId: 'com.example.attendancePanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiHYoyd3AypCiNjVOrS9W9wScI-b5PJhU',
    appId: '1:221902786162:web:1d0169e768ff0fc5127ceb',
    messagingSenderId: '221902786162',
    projectId: 'coin-2ff5f',
    authDomain: 'coin-2ff5f.firebaseapp.com',
    storageBucket: 'coin-2ff5f.firebasestorage.app',
    measurementId: 'G-W099LJBV1M',
  );
}
